# Generated by Django 3.1.4 on 2020-12-24 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201224_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
