# Generated by Django 3.1.4 on 2020-12-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201227_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amt',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
