# Generated by Django 3.1.4 on 2020-12-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_index_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('amt', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Contributions',
        ),
        migrations.AddField(
            model_name='education',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='education',
            name='message',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
