# Generated by Django 3.1.4 on 2021-01-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201227_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cause',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='index',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='eventName',
        ),
        migrations.AddField(
            model_name='events',
            name='eventType',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amt',
            field=models.CharField(max_length=10),
        ),
    ]
